-- MySQL Script generated by MySQL Workbench
-- qua 11 nov 2020 11:07:13 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hemo_clinica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hemo_clinica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hemo_clinica` ;
USE `hemo_clinica` ;

-- -----------------------------------------------------
-- Table `hemo_clinica`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hemo_clinica`.`Status` (
  `id_Status` INT NOT NULL AUTO_INCREMENT,
  `marcado` TINYINT NOT NULL,
  `spera` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hemo_clinica`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hemo_clinica`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `dataNasc` VARCHAR(45) NOT NULL,
  `tipoSanguinio` VARCHAR(45) NOT NULL,
  `cpf`VARCHAR(15)NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hemo_clinica`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hemo_clinica`.`perfil` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT,
  `funcionario` VARCHAR(45) NOT NULL,
  `paciente` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_perfil`),
  INDEX `fk_perfil_usuario_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_usuario`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `hemo_clinica`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hemo_clinica`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hemo_clinica`.`agenda` (
  `id_agenda` INT NOT NULL AUTO_INCREMENT,
  `perfil_id_perfil` INT NOT NULL,
  `Status_id_Status` INT NOT NULL,
  PRIMARY KEY (`id_agenda`),
  INDEX `fk_agenda_perfil1_idx` (`perfil_id_perfil` ASC) VISIBLE,
  INDEX `fk_agenda_Status1_idx` (`Status_id_Status` ASC) VISIBLE,
  CONSTRAINT `fk_agenda_perfil1`
    FOREIGN KEY (`perfil_id_perfil`)
    REFERENCES `hemo_clinica`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_Status1`
    FOREIGN KEY (`Status_id_Status`)
    REFERENCES `hemo_clinica`.`Status` (`id_Status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
